version: "3.3"
services:
  web:
    build: .
    depends_on:
      - db
      - redis
    environment:
      - JWT_SECRET
    ports:
      - "8000:8000"

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql
    expose:
      - "5432"

  redis:
    image: redis:7
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    expose:
      - "6379"

volumes:
  pgdata:
